### ISSUE TITLE
better keyboard in pos mode

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-pay#145]
when opening galoy-pay on mobile, this is what we have:

![2021-12-18 12 26 54](https://user-images.githubusercontent.com/11156370/146641015-e0dafeb2-46db-439f-a43e-50e5b6aac0c0.jpg)

while the UX might be ok for a tipping page (Alice share a link to the world to receive tips), it's not great interface for alice to use this as a point of sales terminal for in person payment.

for it to make a good POS, we should have:
- a keyboard that show on the screens. the keyboard should be designed in a way that is incorporate in the rest of the page, as opposed to the native ios/Android keyboard.

here is an example with how cashapp is doing such keyboard integration:

![IMG_7F7D9531722D-1](https://user-images.githubusercontent.com/11156370/146641159-52ddc585-67dd-4b74-a27a-c567b11231b1.jpeg)

- after putting an amount, the QR code should be displayed, with an invoice that contain an amount (and replace the keyboard)

As it's slight different use case than the tipping page, I think this could be pointed out to the /pos page.

**Comment by Heeeemanshu10** [comment]
Hi, I read this issue and would like to work on it, I think creating a new component and redirecting it to the bitcoin beach could be a possible solution. I'd welcome if someone could help me solve this issue. Thanks.
