### ISSUE TITLE
Fix lightningaddress invoice generation if default wallet is USD

### ISSUE THREAD

**Issue by vindard** [GaloyMoney/galoy-pay#202]
## To Implement Fix

In this [file](https://github.com/GaloyMoney/galoy-pay/blob/3e9a3b3a8c9274e5c3e2ab9ffec6e9311377babe/pages/api/lnurlp/%5Busername%5D.ts#L21), add the `lnUsdInvoiceCreateOnBehalfOfRecipient` mutation as well and then implement by one of:
- (easier) adding a fallback to usd mutation if original mutation fails with the `MutationDoesNotMatchWalletCurrencyError` error
- (harder) poll the currency of the default wallet somehow first and then switch on mutations based on the currency

**Comment by daviroo** [comment]
> ## To Implement Fix
> In this [file](https://github.com/GaloyMoney/galoy-pay/blob/3e9a3b3a8c9274e5c3e2ab9ffec6e9311377babe/pages/api/lnurlp/%5Busername%5D.ts#L21), add the `lnUsdInvoiceCreateOnBehalfOfRecipient` mutation as well and then implement by one of:
> 
> * (easier) adding a fallback to usd mutation if original mutation fails with the `MutationDoesNotMatchWalletCurrencyError` error
> * (harder) poll the currency of the default wallet somehow first and then switch on mutations based on the currency

Would it be better to have a lnDefaultWalletInvoiceCreateOnBehalfOfRecipient endpoint which takes an account ID instead of a wallet ID and always returns an invoice for the default wallet?

**Comment by vindard** [comment]
> Would it be better to have a lnDefaultWalletInvoiceCreateOnBehalfOfRecipient endpoint which takes an account ID instead of a wallet ID and always returns an invoice for the default wallet?

The tricky thing with this is we might fall back to the same issue where we'd need to know if the default wallet for the account was usd/btc to know what amount to pass in to the `amount` property. That's the reason why we have different mutations in some places for USD wallets (to remove ambiguity around `amount` values being passed).
