### ISSUE TITLE
Add print receipt functionality

### ISSUE THREAD

**Issue by Extheoisah** [GaloyMoney/galoy-pay#303]

**Comment by Toheeb-Ojuolape** [comment]
Hi @Extheoisah. Good morning. I have created a pull request with a feature to add print receipt functionality to Galoy pay. You can find screenshots of my implementation below. I look forward to your review on my PR.

<img width="947" alt="Screenshot 2023-03-25 213941" src="https://user-images.githubusercontent.com/45619240/227882151-be46f0be-abd4-4f46-8c9e-9d15cadb7079.png">

<img width="639" alt="Screenshot 2023-03-25 214119" src="https://user-images.githubusercontent.com/45619240/227882225-0a251ced-60e1-4665-a531-a079363a7767.png">

<img width="751" alt="Screenshot 2023-03-25 214054" src="https://user-images.githubusercontent.com/45619240/227882266-647ca0b5-ffb8-4720-8488-6bd3c46d81dc.png">


Kind regards,
Tobi
