### ISSUE TITLE
Clicking QR code should prompt for user default wallet

### ISSUE THREAD

**Issue by Extheoisah** [GaloyMoney/galoy-pay#333]
Current functionality: clicking QR code copies the lightning invoice
Feature request: When user clicks on the QR code, it should show a modal or prompt asking the user to choose which bitcoin wallet(s) installed on their device to pay the invoice.

**Comment by pretyflaco** [comment]
Somewhat related: When clicking on "Pay in Wallet" in a BTCPay invoice on Android Mobile, it opens said modal offering a variety of installed Lightning capable apps, however it does not offer Bitcoin Beach Wallet (despite being installed) 
![image](https://user-images.githubusercontent.com/32958103/207340976-2017a74e-9670-43db-b8b5-f63e13b86659.png)
![image](https://user-images.githubusercontent.com/32958103/207341080-ab7de120-a595-4558-98be-04531efc53eb.png)

@agbegin reproduced similar behavior in IOS, again with multiple other Lightning capable wallets installed, including Bitcoin Beach Wallet, the prompt offers Breez Wallet only. I've read [here](https://github.com/ACINQ/phoenix/issues/251#issue-1143362810) that IOS simply defaults to the last used Lightning wallet.
![image](https://user-images.githubusercontent.com/32958103/207341647-91bd93d6-3cd4-4c53-a2f7-e995847c24e0.png)

**Comment by IgboPharaoh** [comment]
Hello @Extheoisah good day, is this issue still available to be worked on?

**Comment by IgboPharaoh** [comment]
Great, will update the thread as I work on it
