### ISSUE TITLE
lnurl payments fail when users default wallet is USD

### ISSUE THREAD

**Issue by daviroo** [GaloyMoney/galoy-pay#377]
I had a go at [fixing](https://github.com/GaloyMoney/galoy-pay/pull/372) this but for some reason it was not working in BBW (not only did it not fix the USD wallet issue but it also made payments fail for BTC wallets too so I [rolled it back](https://github.com/GaloyMoney/galoy-pay/pull/375)).

**Comment by Extheoisah** [comment]
The issue is not fixed yet, but a temporary solution has been pushed. lnurl payments will temporarily default to BTC wallet regardless of user default wallet.
