### ISSUE TITLE
disable/remove toggle currency button after invoice is created

### ISSUE THREAD

**Issue by Extheoisah** [GaloyMoney/galoy-pay#424]

**Comment by IgboPharaoh** [comment]
Hello @Extheoisah good day, after running the application and going through the codebase I have a quick fix that addresses this issue, and here is a draft pr for your perusal #433  

- The previous user interface 
![image](https://user-images.githubusercontent.com/87058633/227043271-8d3ee596-096d-4775-8607-17bc8da2289e.png)

- The current user interface with the fix
![image](https://user-images.githubusercontent.com/87058633/227043715-fe726556-4b68-46e2-b206-cb4f7d5bda87.png)
