### ISSUE TITLE
Denominate fiat amount in user display currency after payment

### ISSUE THREAD

**Issue by Extheoisah** [GaloyMoney/galoy-pay#454]
When an invoice is paid, we should denominate the amount in the user display currency. In the image below, the display currency is set to GHS (Ghana cedis) (as shown in the localStorage inspector by the right) but the amount showed after payment is denominated in USD.

<img width="1387" alt="Screenshot 2023-04-14 at 14 43 14" src="https://user-images.githubusercontent.com/60826700/232060473-737ba743-2858-4c6a-aab4-c9a1add1f4e9.png">

**Comment by ntheile** [comment]
fixed in https://github.com/GaloyMoney/galoy-pay/pull/459
