### ISSUE TITLE
need backoff for polled query

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-pay#57]
currently when an invoice is being created, there is a [poll](https://github.com/GaloyMoney/lnpage/blob/85d0e92c73f890fcd7ae40acc2d37175be055268/app/src/components/receive.js#L58) to know if the invoice has been paid

the intention is that if the invoice has been paid, then there should be a checkmark letting know the payer that the payment has been received

but maybe people are probably leaving their tab open, this result with a lot of unnecessary poll/ load pressure to our server.

so we should have a backoff mechanism after some time (maybe 30 min or 1h).

maybe also using subscription would avoid this issue (@samerbuna)

**Comment by samerbuna** [comment]
Yes. We need to convert this into a subscription.

**Comment by nicolasburtey** [comment]
subscription has been done
